name: kiprotect-docs
url: http://localhost:8111
# we add .html to the links (to be able to serve them with a dev server)
articles-per-page: 5
path: /
static-path: docs/static
pygments:
  style: tango
languages:
  #these pages will be copied to all languages
  $all:
    pages:
      - src: common/404.html
        hidden: true
        footer: false
        attrs:
          sitemap: false
        title: 404
        slug: '404'
        name: '404'
translations:
  $include: translations/index.yml
context:
  env: development
